# Generated by Django 5.1 on 2024-11-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favoritedby",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
